# Generated by Django 5.2.4 on 2025-07-25 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_apartmentcode_account_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='myapp.apartment'),
        ),
    ]
