# Generated by Django 5.2.4 on 2025-07-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_member_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('living', 'Living'), ('moved', 'Moved')], default='living', max_length=6),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('resident', 'Resident')], default='resident', max_length=50),
        ),
    ]
