# Generated by Django 5.2.4 on 2025-07-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_apartment_status_alter_resident_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
