# Generated by Django 5.2.4 on 2025-07-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_resident_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('living', 'Living'), ('left', 'Left')], default='living', max_length=6),
        ),
    ]
