# Generated by Django 5.2.4 on 2025-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_resident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='hometown',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
