# Generated by Django 5.2.4 on 2025-07-28 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_resident_hometown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('living', 'Living'), ('left', 'Left'), ('temporaryresidence', 'Temporaryresidence'), ('temporaryabsence', 'Temporaryabsence')], default='living', max_length=20),
        ),
        migrations.CreateModel(
            name='TemporaryAbsence',
            fields=[
                ('absenceId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryResidence',
            fields=[
                ('residenceId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.resident')),
            ],
        ),
    ]
