# Generated by Django 5.2.4 on 2025-07-28 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_resident_status_temporaryabsence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='apartment',
        ),
        migrations.AddField(
            model_name='apartment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
