# Generated by Django 5.2.4 on 2025-07-29 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_account_apartment_apartment_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleId', models.AutoField(primary_key=True, serialize=False)),
                ('licensePlate', models.CharField(max_length=10, unique=True)),
                ('vehicleType', models.CharField(choices=[('car', 'Car'), ('motorbike', 'Motorbike'), ('bike', 'Bike'), ('other', 'Other')], default='car', max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apartment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.resident')),
            ],
        ),
    ]
