# Generated by Django 5.2.4 on 2025-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_resident_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='idNumber',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
