# Generated by Django 5.2.4 on 2025-07-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_resident_email_alter_resident_idnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isMember',
            field=models.BooleanField(default=True),
        ),
    ]
