# Generated by Django 5.2.4 on 2025-07-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_member_ismember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='idNumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
