# Generated by Django 5.2.4 on 2025-07-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_resident_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
