# Generated by Django 5.2.4 on 2025-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_resident_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
    ]
