# Generated by Django 5.2.4 on 2025-07-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_resident_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['apartmentCode__apartmentCode', 'residentId']},
        ),
    ]
