# Generated by Django 5.2.4 on 2025-07-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_resident_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['member__apartment__apartmentCode', 'residentId']},
        ),
    ]
