# Generated by Django 5.2.4 on 2025-08-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_resident_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['apartment', 'resident']},
        ),
    ]
