# Generated by Django 5.2.4 on 2025-08-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='timeregister',
            field=models.DateField(null=True),
        ),
    ]
