# Generated by Django 5.2.4 on 2025-08-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_vehicle_timeregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('inuse', 'Inuse'), ('deleted', 'Deleted')], default='inuse', max_length=7),
        ),
    ]
