# Generated by Django 5.2.4 on 2025-08-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_vehicle_licenseplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='licensePlate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
