# Generated by Django 5.2.4 on 2025-08-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_vehicle_licenseplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['apartment', 'memberId']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['apartment', 'resident', 'vehicleId']},
        ),
    ]
