# Generated by Django 5.2.4 on 2025-08-07 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_member_options_alter_vehicle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('collectionId', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('createdDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentFee',
            fields=[
                ('apartmentFeeId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=6)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apartment')),
                ('feeCollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.feecollection')),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('feeName', models.CharField(max_length=200)),
                ('typeDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('isRequired', models.BooleanField(default=True)),
                ('appliedScope', models.CharField(choices=[('all', 'All'), ('some', 'Some')], default='all', max_length=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('applicableApartments', models.ManyToManyField(blank=True, to='myapp.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='feecollection',
            name='feeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.feetype'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transactionId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('paymentDate', models.DateField()),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending'), ('failed', 'Failed')], default='successful', max_length=10)),
                ('apartmentFee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apartmentfee')),
            ],
        ),
    ]
