# Generated by Django 5.2.4 on 2025-08-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_feecollection_apartmentfee_feetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='amountDefault',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
