# Generated by Django 5.2.4 on 2025-08-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_feetype_amountdefault'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentfee',
            options={'ordering': ['feeCollection', 'apartment']},
        ),
        migrations.AlterModelOptions(
            name='feecollection',
            options={'ordering': ['year', 'month', 'feeType']},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['paymentDate', 'apartmentFee']},
        ),
    ]
