# Generated by Django 5.2.4 on 2025-08-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_apartmentfee_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['member', 'vehicleId']},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='resident',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.member'),
        ),
    ]
