# Generated by Django 5.2.4 on 2025-08-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_vehicle_options_remove_vehicle_apartment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feecollection',
            options={'ordering': ['year', 'month', 'createdDate']},
        ),
    ]
