# Generated by Django 5.2.4 on 2025-08-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_feecollection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feecollection',
            options={'ordering': ['year', 'month', '-createdDate', 'feeType']},
        ),
    ]
