# Generated by Django 5.2.4 on 2025-08-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_feecollection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentfee',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('deleted', 'Deleted')], default='unpaid', max_length=7),
        ),
    ]
