# Generated by Django 5.2.4 on 2025-08-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_apartmentfee_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['-typeId']},
        ),
    ]
